<!-- Heading -->
# 4 Homework
<!-- OL -->

1.	What does one need to do to use a module?
Use – Import welcome- to import it into your program.

2.	Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.
Import datetime as dt
A = dt.datetime.now()
Print(“current Date and Time…”, a)

3.	What is a benefit of using Exception handling?
Remove/separate error handling code from main code.

4.	NumPy arrays are like what Python data type?
List
5.	What is one of the main benefits of using NumPy arrays.
Less memory, Fast, convenient

6.	What is one of the main requirements about the 'dtype' of NumPy arrays?
A data type object implements the fixed size of memory corresponding to an array.

7.	Of the 10 uses of NumPy, name 2.
Searching, sorting and counting. Linear algebra.

8.	Name one of the other libraries we'll use with NumPy?
Pandas

9.	What is the shape of NumPy arrays?
Shape = rows
10.	What is a Tensor?
An array with 3+ dimensions

11.	Name a reason why it's better using NumPy for Data Analysis than using a Python List?
NumPy is faster and more compact than Python lists.

12.	When creating an "empty" array, where do the elements come from?
The initial content is random and depends on the state of memory. 




In [7]:
# Use the DateTime module to get Current Date and Time, and save it to a variable.
#  Then extract just the Full month name form that variable.

import datetime as dt

# Get Current Date and Time
a = dt.datetime.now()
print("Current Date and Time ...", a)

import datetime
Today = datetime.datetime.now()

print("Month ...", Today.strftime("%B"))


Current Date and Time ... 2023-02-19 20:14:00.182015
Month ... February


In [35]:
# Write a simple function that takes 2 parameters -- a first name and a day name.

#Set a default value for the day name of Sunday.    
#Have the function print out a greeting 
# -- using the parameters 
# -- that says something like "Hi first-name! Happy day-name!". -
# --Remember to use the variables in the greeting to replace first-name and day-name.
#Invoke this function with 2 variables.
#Invoke this function with 1 variable only.

def nameday(name,day = "Sunday"):
    print("Hi,", name,"! Happy", day, "!")
    
nameday("Kyrah")


Hi, Kyrah ! Happy Sunday !


In [62]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2).
#  You can use the reshape method -- .reshape()

import numpy as np
aArray = np.array(([2,3,4,5], [1,2,3,4], [2,3,4,5]))
print("newShape1 ...\n", aArray)

newShape3 = aArray.reshape(2, 3, 2)
print("\nnewShape3 ...\n", newShape3)


newShape1 ...
 [[2 3 4 5]
 [1 2 3 4]
 [2 3 4 5]]

newShape3 ...
 [[[2 3]
  [4 5]
  [1 2]]

 [[3 4]
  [2 3]
  [4 5]]]


In [68]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

arrayspace = np.linspace(0,20, 6)
print(arrayspace)

[ 0.  4.  8. 12. 16. 20.]


In [71]:
#Make a Deep Copy of the above array you created.

import copy
arrayspaced = copy.deepcopy(arrayspace)

What are 2 reasons we use NumPy arrays over Python Lists
NumPy uses much less memory to store data, and its faster.